# SPDX-FileCopyrightText: 2025 mkanke-real <mikekanke@gmail.com>
#
# SPDX-License-Identifier: MIT

- type: entity
  parent: BaseMail
  id: MailSecurityJusticeHelm
  suffix: Justice Helm
  components:
  - type: Mail
    contents:
    - id: ClothingHeadHelmetJustice

- type: entity
  parent: BaseMailLarge
  id: MailSecurityPracticeShotgun
  suffix: Practice Shotgun
  components:
  - type: Mail
    contents:
    - id: WeaponShotgunSawnEmpty
    - id: BoxShotgunPractice

- type: entity
  parent: BaseMailLarge
  id: MailSecurityPracticeBomb
  suffix: Practice Syndicate Bomb
  components:
  - type: Mail
    contents:
    - id: SyndicateBombFake